CommerceClient/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ServiceModel;
using CommerceClient.HomeServiceReference;
using AutoMapper;
using CommerceClient.Models;

namespace CommerceClient.Controllers
{
    public class HomeController : Controller
    {
     
        HomeServiceClient objHome = new HomeServiceClient();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AllMoviePage()
       
        {
           // CartServiceReference.
            var movielist = objHome.DisplayAllProducts();
            var itemlist = new List<ProductModel>();

            if (movielist.Any())
            {
                //Mapper initialization and creation mapping from DB to model
                // Mapper.Initialize(cfg => cfg.CreateMap<Product, NewCommerce.Models.ProductModel>().ForMember(dest => dest.Category.CategoryName, opt => opt.MapFrom(src => src.Category.CategoryName)));
                Mapper.Initialize(cfg => { cfg.CreateMap<Producttype, ProductModel>(); cfg.CreateMap<Categorytype, CategoryModel>(); });
                foreach (var item in movielist)
                {
                    ProductModel userModel =
                      Mapper.Map<Producttype, ProductModel>(item);
                    userModel.Category.CategoryName = item.Category.CategoryName;
                    itemlist.Add(userModel);


                }
            }

            return View(itemlist);

        }

        public ActionResult DisplayProduct_ByCategory(string CategoryName)
        {
            var movielist = objHome.DisplayProductsByCategory(CategoryName);
            var itemlist = new List<ProductModel>();
            if (movielist.Any())
            {
                //Mapper initialization and creation mapping from DB to model
                // Mapper.Initialize(cfg => cfg.CreateMap<Product, NewCommerce.Models.ProductModel>().ForMember(dest => dest.Category.CategoryName, opt => opt.MapFrom(src => src.Category.CategoryName)));
                Mapper.Initialize(cfg => { cfg.CreateMap<Producttype,ProductModel>(); cfg.CreateMap<Categorytype,CategoryModel>(); });
                foreach (var item in movielist)
                {
                    ProductModel userModel =
                    Mapper.Map<Producttype,ProductModel>(item);
                    userModel.Category.CategoryName = item.Category.CategoryName;
                    itemlist.Add(userModel);
                }
            }

            return View(itemlist);
        }

    }
}

CommerceClient/Controllers/MoviePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Web.Script.Serialization;
using CommerceClient.HomeServiceReference;
using AutoMapper;
using CommerceClient.Models;

namespace CommerceClient.Controllers
{
    public class MoviePageController : Controller
    {
        HomeServiceClient objHome = new HomeServiceClient();
        // GET: /MoviePage/
        

        public ActionResult MovieReview(string name)
        {
            

            var movieData = objHome.GetMovie(name);
            Mapper.Initialize(cfg=>cfg.CreateMap<ImdbEntityType,ImdEntity>());
            ImdEntity obj = Mapper.Map<ImdbEntityType, ImdEntity>(movieData);

                //test
                List<SelectListItem> QuantityList = new List<SelectListItem>();

                int quantity = Convert.ToInt32(objHome.GetQuantity(name));

                for (int i = 1; i <= quantity; i++)
                {
                    QuantityList.Add(new SelectListItem { Text = i.ToString() });
                    //new SelectListItem { Text = i.ToString() });
                }
                TempData["dropdownQTy"] = QuantityList;


                return View(obj);
            }

        

        [HttpPost]
        public ActionResult CartAdd(string hdn)
        {


            var a = Request.Params["CartAdd"];
            var b = Request["CartAdd"];
            return View();

        }
	}
}

CommerceClient/Views/Home/AllMoviePage.cshtml
@model IEnumerable<CommerceClient.Models.ProductModel>
@{
    ViewBag.Title = "AllMoviePage";
    Layout = "~/Views/Shared/_Layout4.cshtml";
}

<h2>All Movies</h2>

<div style="padding-left: 50px;width:650px">
    <table style="height: 300px; width: 650px; font-family: PacificoRegular">
        @{var counter = 1; }
        <tr style="padding-top: 20px">
            @foreach (var item in Model)
            {

                <td style="height: 100px; width: 200px;">
                    @Html.DisplayFor(modelItem => item.ProductName)
                    <a href="@Url.Action("MovieReview", "MoviePage", new { name = item.ProductName})">

                        <img src="@Url.Content(item.ImagePath)" style="border-width: 8px; border-color: #fff #fff transparent transparent; background: #fff; -moz-border-radius: 5px 5px 5px 5px; border-radius: 5px 5px 5px 5px; display: block; height:150px; width:200px" />
                    </a>
                    <br />
                    Price: Rs. @Html.DisplayFor(modelItem => item.Price)
                    <br />
                    Quantity: @Html.DisplayFor(modelItem => item.QuantityAvailable)
                    <br />
                    Category: @Html.DisplayFor(modelItem => item.Category.CategoryName)
                </td>
                <td><br /><br /></td>
                if (counter % 3 == 0)
                {
                    @:</tr><tr><td><br /></td></tr><tr>
                }
                counter++;


            }
        </tr>
    </table>
</div>

CommerceClient/Views/Home/DisplayProduct_ByCategory.cshtml
@model IEnumerable<CommerceClient.Models.ProductModel>

    @{
        ViewBag.Title = "DisplayProduct_ByCategory";
        Layout = "~/Views/Shared/_Layout4.cshtml";
    }


<div style="padding-left: 50px;width:650px">
    <table style="height: 300px; width: 650px; font-family: PacificoRegular">
        @{var counter = 1; }
        <tr style="padding-top: 20px">
            @foreach (var item in Model)
            {

                <td style="height: 100px; width: 200px;">
                    @Html.DisplayFor(modelItem => item.ProductName)
                    <a href="@Url.Action("MovieReview", "MoviePage", new { name = item.ProductName})">

                        <img src="@Url.Content(item.ImagePath)" style="border-width: 8px; border-color: #fff #fff transparent transparent; background: #fff; -moz-border-radius: 5px 5px 5px 5px; border-radius: 5px 5px 5px 5px; display: block; height:150px; width:200px" />
                    </a>
                    <br />
                    Price: Rs. @Html.DisplayFor(modelItem => item.Price)
                    <br />
                    Quantity: @Html.DisplayFor(modelItem => item.QuantityAvailable)
                    <br />
                    Category: @Html.DisplayFor(modelItem => item.Category.CategoryName)
                </td>
                <td><br /><br /></td>
                if (counter % 3 == 0)
                {
                    @:</tr><tr><td><br /></td></tr><tr>
                }
                counter++;


            }
        </tr>
    </table>
</div>

CommerceClient/Views/Home/Index.cshtml
@model IEnumerable<CommerceClient.Models.ProductModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout3.cshtml";
}


<br /><br />
<div id="welcome_slogan">
    <h3><span>Relive  your  everyday  Movie  Experience....</span></h3>
</div>
<br /><br />
<div style="padding-left: 150px;width:600px" class="zoomin">
    <table style="height: 300px; width: 600px; font-family: PacificoRegular">

        <tr style="padding-top: 150px">
            <td style="height: 100px; width: 200px;">
                <a href="@Url.Action("DisplayProduct_ByCategory", "Home",new {CategoryName ="Comedy"})">
                    <img src="@Url.Content("~/ImagesMovies/frontpage/comic(1).jpg")" style="border-radius: 50%" />

                </a>
                <br />
                &nbsp;&nbsp;&nbsp; <h3 style="font-family: PacificoRegular">Comedy</h3>
            </td>
            <td>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </td>
            <td style="height: 100px; width: 200px;">
                <a href="@Url.Action("DisplayProduct_ByCategory", "Home",new {CategoryName ="Horror"})">
                    <img src="@Url.Content("~/ImagesMovies/frontpage/horror170x170.jpg")" style="border-radius: 50%" />

                </a>
                <br />
                &nbsp;&nbsp;&nbsp; <h3 style="font-family: PacificoRegular">Horror</h3>
            </td>
            <td>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </td>

            <td style="height: 100px; width: 200px;" class="zoomin">
                <a href="@Url.Action("DisplayProduct_ByCategory", "Home",new {CategoryName ="Action"})">
                    <img src="@Url.Content("~/ImagesMovies/frontpage/Action170x170.jpg")" style="border-radius: 50%" />

                </a>
                <br />
                &nbsp;&nbsp;&nbsp; <h3 style="font-family: PacificoRegular">Action</h3>
            </td>

        </tr>
    </table>
</div>

<div style="padding-left: 230px;width:400px" class="zoomin">
    <table style="height: 300px; width: 530px; font-family: Wyllam Regular">

        <tr style="padding-top: 400px">

            <td style="height: 100px; width: 100px;">
                <a href="@Url.Action("DisplayProduct_ByCategory", "Home",new {CategoryName ="Thriller"})">
                    <img src="@Url.Content("~/ImagesMovies/jw_1_170x170.jpg")" style="border-radius: 50%" />
                </a>
                <br />
                &nbsp;&nbsp;&nbsp;<h3 style="font-family: PacificoRegular">Thriller</h3>
            </td>
            @*<td>

                </td>*@
            <td style="height: 100px; width: 100px;">
                <a href="@Url.Action("DisplayProduct_ByCategory", "Home",new {CategoryName ="Suspence"})">
                    <img src="@Url.Content("~/ImagesMovies/frontpage/suspence_170x170.jpg")" style="border-radius: 50%" />
                    
                </a>
                <br />
                &nbsp;&nbsp;&nbsp; <h3 style="font-family: PacificoRegular">Suspence</h3>
            </td>

        </tr>

    </table>
</div>